---
title: "class10"
author: "Muhammad Tariq"
date: "2025-05-01"
output:
  pdf_document: default
---
##Setup
```{r}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

# Load all necessary packages (assumes already installed)
library(tidyverse)
library(tinytex)
library(skimr)
library(corrplot)
library(ggrepel)
library(plotly)
```


###1. 1. Importing candy data
```{r}
candy_file <- "candy-data.csv"
candy <- read.csv("candy-data.csv", row.names=1)
head(candy)
```
```{r}
#Q1 How many different candy types are in the dataset?
nrow(candy)
```
 There are 85 different candy types in this dataset

```{r}
# Q2: Number of fruity candy types
sum(candy$fruity == 1)
```
There are 38 number of fruity candies

###2. What is your favorate candy?


```{r}
#Q3. What is your favorite candy in the dataset and what is it’s winpercent value?


candy["Air Heads", "winpercent"]

```
The winercent is 52% for Air Heads (fav candy)

```{r}
#Q4. What is the winpercent value for “Kit Kat”?
candy["Kit Kat", "winpercent"]

```
The winpercent is 77% for kitkat

```{r}
#Q5. What is the winpercent value for “Tootsie Roll Snack Bars”?
candy["Tootsie Roll Snack Bars", "winpercent"]

```
The winpercent is 50% for tootsie roll snack bars.

##Skim Function
```{r}
library("skimr")
skim(candy)
```

```{r}

# Q6. Any variable on a different scale? (Check 'sugarpercent', 'pricepercent', 'winpercent')
# 'winpercent', 'sugarpercent', and 'pricepercent' are continuous, others are binary
# Confirms variable distributions

# Q7. 0 = does not have chocolate; 1 = has chocolate (binary)
# Q7. Interpretation of 0 and 1 in 'chocolate' column

# 0 = no chocolate, 1 = contains chocolate
table(candy$chocolate)  # Shows count of each
```
```{r}
# Q8. Histogram of winpercent
hist(candy$winpercent, main = "Histogram of Win Percent", xlab = "Win Percent")
```

```{r}
# Q9–Q10.
# Check symmetry visually
# Center (mean)
mean(candy$winpercent)
```
```{r}
# Q11. Mean winpercent for chocolate vs fruity candies
mean(candy$winpercent[as.logical(candy$chocolate)])
mean(candy$winpercent[as.logical(candy$fruity)])
```

```{r}
# Q12. Statistical test (Welch t-test)
t.test(candy$winpercent[as.logical(candy$chocolate)],
       candy$winpercent[as.logical(candy$fruity)])
```

```{r}
# Q13. 5 least liked candies
candy %>% arrange(winpercent) %>% head(5)
```

```{r}
# Q14. 5 most liked candies
candy %>% arrange(desc(winpercent)) %>% head(5)

```

```{r}
# Q15. Barplot of winpercent
ggplot(candy) +
  aes(x = winpercent, y = rownames(candy)) +
  geom_col()
```

```{r}
# Q16. Improve barplot with reorder
ggplot(candy) +
  aes(x = winpercent, y = reorder(rownames(candy), winpercent)) +
  geom_col()
```

```{r}
# Color vector
my_cols <- rep("black", nrow(candy))
my_cols[as.logical(candy$chocolate)] <- "chocolate"
my_cols[as.logical(candy$bar)] <- "brown"
my_cols[as.logical(candy$fruity)] <- "pink"

# Improved barplot with colors
ggplot(candy) +
  aes(x = winpercent, y = reorder(rownames(candy), winpercent)) +
  geom_col(fill = my_cols)
```

```{r}
# Q17. Worst ranked chocolate candy
candy[as.logical(candy$chocolate), ] %>%
  arrange(winpercent) %>%
  head(1)
```

```{r}
# Q18. Best ranked fruity candy
candy[as.logical(candy$fruity), ] %>%
  arrange(desc(winpercent)) %>%
  head(1)
```

```{r}
# Q19. Best value candy (high winpercent, low pricepercent)
ggplot(candy) +
  aes(x = winpercent, y = pricepercent, label = rownames(candy)) +
  geom_point(col = my_cols) +
  geom_text_repel(col = my_cols, size = 3.3, max.overlaps = 5)
```

```{r}
# Q20. Top 5 most expensive candies + least popular among them
ord <- order(candy$pricepercent, decreasing = TRUE)
head(candy[ord, c("pricepercent", "winpercent")], n = 5)
```

```{r}
# Q21. Lollipop chart
ggplot(candy) +
  aes(x = pricepercent, y = reorder(rownames(candy), pricepercent)) +
  geom_segment(aes(xend = 0, yend = reorder(rownames(candy), pricepercent)),
               col = "gray40") +
  geom_point()
```

```{r}
# Q22–Q23. Correlation matrix
cij <- cor(candy)
corrplot(cij)

#The most positively correlated variables are chocolate and bar. This makes sense because chocolate candies are often in bar form. You can verify this in the corrplot by looking at the darkest/highest value.
```

```{r}
# Q24. PCA
pca <- prcomp(candy, scale. = TRUE)
summary(pca)
```

```{r}
# Base R plot of PC1 vs PC2
plot(pca$x[, 1:2], col = my_cols, pch = 16)

# ggplot PCA
my_data <- cbind(candy, pca$x[, 1:3])
p <- ggplot(my_data) +
  aes(x = PC1, y = PC2,
      size = winpercent / 100,
      text = rownames(my_data),
      label = rownames(my_data)) +
  geom_point(col = my_cols)

# PCA plot with labels
p + geom_text_repel(size = 3.3, col = my_cols, max.overlaps = 7) +
  theme(legend.position = "none") +
  labs(
    title = "Halloween Candy PCA Space",
    subtitle = "Colored by type: chocolate bar (dark brown), chocolate other (light brown), fruity (red), other (black)",
    caption = "Data from 538"
  )

# Optional: interactive plot
ggplotly(p)

# PCA loadings for PC1
par(mar = c(8, 4, 2, 2))
barplot(pca$rotation[, 1], las = 2, ylab = "PC1 Contribution")
```

